# Generated by Django 2.1.3 on 2019-03-12 11:13

import apps.common.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('name', models.TextField()),
                ('db_settings', models.BinaryField(editable=True)),
                ('db_type', models.CharField(max_length=256)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('compute_time', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In progress'), ('done', 'Done'), ('error', 'Error')], default='created', max_length=32)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(max_length=128)),
                ('absolute_path', models.CharField(max_length=1024)),
                ('file_size', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dataframe_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('columns_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('preview_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('absolute_path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('compute_time', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In progress'), ('done', 'Done'), ('error', 'Error')], default='created', max_length=32)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(max_length=128)),
                ('name', models.TextField()),
                ('query_text', models.TextField(blank=True, null=True)),
                ('saved', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_database_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasources.DatabaseSource')),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataframe',
            name='source_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasources.FileDataSource'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='source_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasources.Query'),
        ),
    ]
