export const RESET_DATAFRAME_COLUMNS = "RESET_DATAFRAME_COLUMNS";
export const GET_DATAFRAME_COLUMNS_SUCCESS = "GET_DATAFRAME_COLUMNS_SUCCESS";
export const GET_DATAFRAME_COLUMNS_ERROR = "GET_DATAFRAME_COLUMNS_ERROR";
export const SET_COLUMN_USAGE = "SET_COLUMN_USAGE";
