export const DATAFRAME_PREVIEW_LOADING = "DATAFRAME_PREVIEW_LOADING";
export const GET_DATAFRAME_PREVIEW_SUCCESS = "GET_DATAFRAME_PREVIEW_SUCCESS";
export const GET_DATAFRAME_PREVIEW_ERROR = "GET_DATAFRAME_PREVIEW_ERROR";
