export const GET_COLUMNS_USAGE_SUCCESS = "GET_COLUMNS_USAGE_SUCCESS";
export const GET_COLUMNS_USAGE_LIST_SUCCESS = "GET_COLUMNS_USAGE_LIST_SUCCESS";
export const DELETE_COLUMNS_USAGE = "DELETE_COLUMNS_USAGE";
export const ADD_COLUMNS_USAGE = "ADD_COLUMNS_USAGE";
